### ISSUE TITLE
Find companies to practice interviewing

### ISSUE THREAD

**Issue by Starsa** [Starsa/Mentorship#14]
Aim to apply to 5 companies a week for practice, list companies in tracker and link here
- [x] Find companies/jobs you may not want but apply and work on interview prep.
- [x] Apply
- [ ] Interview

**Comment by Starsa** [comment]
**Job List**
- [ ] [Atom Finance](https://www.linkedin.com/jobs/view/2612246551/?refId=ba041f45-3e3f-4dd2-95f5-16007857042c&trk=flagship3_job_home_savedjobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_myitems_savedjobs%3B7rEhhM2NQjWpO%2FTZQKLmFg%3D%3D)

- [ ] - [American Express](https://www.linkedin.com/jobs/view/2619407475/?refId=ba041f45-3e3f-4dd2-95f5-16007857042c&trk=flagship3_job_home_savedjobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_myitems_savedjobs%3B7rEhhM2NQjWpO%2FTZQKLmFg%3D%3D)

- [ ] - [Vroom](https://www.linkedin.com/jobs/view/2615530417/?refId=ba041f45-3e3f-4dd2-95f5-16007857042c&trk=flagship3_job_home_savedjobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_myitems_savedjobs%3B7rEhhM2NQjWpO%2FTZQKLmFg%3D%3D)

- [ ] - [Hinge](https://www.linkedin.com/jobs/view/2619858406/?refId=ba041f45-3e3f-4dd2-95f5-16007857042c&trk=flagship3_job_home_savedjobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_myitems_savedjobs%3B7rEhhM2NQjWpO%2FTZQKLmFg%3D%3D)

**Comment by CLuiz** [comment]
Can you update this card with progress? Ie, where have you interviewed, what other companies have been added to the list.

**Comment by Starsa** [comment]
created a new card, if I interview I will update this card and unarchive.
