### ISSUE TITLE
Elevtor Pitch

### ISSUE THREAD

**Issue by Starsa** [Starsa/Mentorship#16]
Work on Elevator pitch every week 

- [x] have an elevator pitch ready weekly to discuss

**Comment by CLuiz** [comment]
There are some good points in this article. Make sure you are positioning your background as an asset vs a liability.

https://www.northeastern.edu/graduate/blog/elevator-pitch-example/

**Comment by Starsa** [comment]
Elevator pitch:

> I have a pretty unique background as a musician; an opera singer actually. On a fundamental level, I was analyzing the page, both the music and about 14 different languages, and translating that for my audience. It set me up for a pivot into a more analytics career path. The last few years I have worked in data-driven roles learning new technologies and continuing to work with languages in quantitative ways. Last year I decided to level up and enroll in an Apprenticeship, working with a Data Science mentor twice a week and honing in on more advanced machine learning techniques and NLP tools which I have been able to use on a few projects. Right now I am working with a recruiting company and acting as a Data Science consultant.
