### ISSUE TITLE
NLP Tutorial Resources

### ISSUE THREAD

**Issue by CLuiz** [Starsa/Mentorship#17]
Collect nlp tutorial resources in this card.

https://www.machinecurve.com/index.php/getting-started-with-huggingface-transformers/

**Comment by Starsa** [comment]
[Hugging Face](https://huggingface.co/course/chapter1)

**Comment by Starsa** [comment]
Found a 4-course specialization on NLP by Andrew Ng on Coursera. Started the first course; could have completed it by end of the week.
[Linked here](https://www.coursera.org/specializations/natural-language-processing)
