### ISSUE TITLE
Daily ML Card Review 

### ISSUE THREAD

**Issue by CLuiz** [Starsa/Mentorship#18]
Cont from #7 
### Acceptance Criteria
- [ ] Monday
- [ ] Tuesday
- [ ] Wednesday
- [ ] Thursday
- [ ] Friday
- [ ] Saturday
- [ ] Sunday

**Comment by Starsa** [comment]
- Gradient Descent 
- Keneling/ kernel trick
- Regularization- when to use vs normalization vs scaling (I seem to put all these together in the same space)
- l1, l2 eleasticnet ( I have been asked about these before in an interview, can't say I can actually speak to them!
