### ISSUE TITLE
Apply to five companies

### ISSUE THREAD

**Issue by CLuiz** [Starsa/Mentorship#20]
### Acceptance Criteria

- [x] Apply to at least five companies/roles by July 17th and capture them below.

**Comment by CLuiz** [comment]
@Starsa please add the companies as you apply. I want to get ahead of intros if I connected to any folks there.

**Comment by Starsa** [comment]
1. [Data Analyst- Doximity](https://workat.doximity.com/positions/?gh_jid=2339187)
2. [NLP Data Scientist](https://www.linkedin.com/jobs/view/2642361853)
3. [Realm-Machine Learning Data Scientist](https://www.linkedin.com/jobs/view/machine-learning-data-scientist-at-realm-2606510162/)
4. [Carta- Data Scientist Machine Learning](https://boards.greenhouse.io/carta/jobs/4541726003)
5. [Civis Analytics- Applied Data Scientist](https://www.linkedin.com/jobs/view/2618259730/?alternateChannel=search&refId=cCDnJk9TaRd5yvMXzNN49w%3D%3D&trackingId=%2BVthmYVH6JYpntumXTsVZw%3D%3D)
Applied to these positions.

**Comment by Starsa** [comment]
**Keywords from the Req's that over lap**

- Remote
- Helping/help, problem solving
- collaborate, team, ccross-functional
- 2 years exp.
- Python
- EDA
- Visualization, insight
- Storytelling*, communication
- curiosity, analytical mindset
- NLP
- building a model
