### ISSUE TITLE
Apply to 10 companies

### ISSUE THREAD

**Issue by Starsa** [Starsa/Mentorship#23]
- [x] Apply to ten companies weekly

**Comment by Starsa** [comment]
Companies applied to:

1. [Ribbon](https://www.ribbonhome.com/job?gh_jid=5362506002&gh_src=a5f86a9f2us) **-_rejected_**
2. [Codecademy](https://www.builtinnyc.com/job/data/data-scientist-machine-learning/88672) **-_rejected_**
3. [Grammarly](https://www.grammarly.com/jobs/product/data-scientist?gh_jid=2589481) 
4. [Axios](https://ai-jobs.net/job/7507-senior-data-scientist/)
5. [Scribd](https://ai-jobs.net/job/8059-data-scientist/)
6. [Hyperscience](https://ai-jobs.net/job/7698-senior-nlp-engineer/)
7. [Relativity](https://ai-jobs.net/job/7770-data-scientist-analytics/)
8. [Quora](https://ai-jobs.net/job/8183-data-scientist-remote/) **-_rejected_**
9. [EasyPost](https://boards.greenhouse.io/easypost/jobs/5345665002)
10. [National research Group](https://www.linkedin.com/jobs/view/data-scientist-at-national-research-group-2660975946/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic)

**Comment by CLuiz** [comment]
Already rejected from Code academy? Form letter or what?

**Comment by Starsa** [comment]
Email that reads:

Hi Sara,
 
Thanks so much for your interest in the Data Scientist, Machine Learning role here at Codecademy. Unfortunately, we will not be moving forward with your candidacy for this role. As we continue to grow our team, we'd love to stay in touch and consider you for any future roles that might be a better fit.
 
Thank you again for your time and interest in Codecademy!
 
All the best,

Codecademy Talent Team

**Comment by Starsa** [comment]
Hi Sara,

Thank you for applying to Ribbon! We receive applications from qualified candidates daily and are flattered that you would consider a career here. While our team was impressed by your background, we currently don't see a strong mutual fit at this time for the role.
 
We appreciate you taking the time to learn more about Ribbon and encourage you to continue visiting our Careers page, as we will be adding new roles on a regular basis that may be a better fit.
 
All the best for your future!
 
Warmly,
Ribbon People Team

**Comment by CLuiz** [comment]
This is great. Gotta get all the rejections out of the way first. You're doing great!
