### ISSUE TITLE
Networking

### ISSUE THREAD

**Issue by Starsa** [Starsa/Mentorship#25]
Track networking like linkedin outreach & any other networking efforts here (ie, meetup research)

**Comment by Starsa** [comment]
Met with Karen Farbman at Atozdata (7/20/21)
discussed her role and the different projects she is working on. Not interested in working there, but she did mention how much research goes into the role and that it is not just building models and cleaning data.

**Comment by CLuiz** [comment]
Can you link the req here? Or reference the other issue where it is linked?

**Comment by Starsa** [comment]
No req, just networking will network with 3 people from positions I want!

**Comment by Starsa** [comment]
**Horizon Media**

Reached out to recruiter and contact at the company to revisit a conversation. I interviewed for a position there in May and the recruiter tried to reconnect end of May, but we never spoke due to scheduling. There are plenty of roles, and I have a good referral.

[Horizon Media Open Roles](https://horizonmedia.wd1.myworkdayjobs.com/CareerOpportunities/0/refreshFacet/318c8bb6f553100021d223d9780d30be)

**Comment by Starsa** [comment]
Optum- A family friend, [Nicole](https://www.linkedin.com/in/nicolemagdziarz/) is Director of Product- Oncology. 

Think this Req looks pretty cool! 
[NLP Data Scientist](https://www.linkedin.com/jobs/view/2647544204/?refId=a6e4101f-8d56-4e26-95fa-1f9af42b0fea)

**Comment by CLuiz** [comment]
> Optum- A family friend, [Nicole](https://www.linkedin.com/in/nicolemagdziarz/) is Director of Product- Oncology.
> 
> Think this Req looks pretty cool!
> [NLP Data Scientist](https://www.linkedin.com/jobs/view/2647544204/?refId=a6e4101f-8d56-4e26-95fa-1f9af42b0fea)

That one looks really good, particularly w/ a strong recommendation from Nicole! My only Q would be whether it will meet your desired salary level. Did Nicole have any insight there?
