### ISSUE TITLE
Leetcode

### ISSUE THREAD

**Issue by Starsa** [Starsa/Mentorship#26]
Discuss Leetcode challenges you have worked on and any that you cannot complete in 15 minutes or less to review with @CLuiz

**Comment by Starsa** [comment]
Unable to solve what should be easy codes:

- merge two sorted lists
- valid parentheses

(I did order 2 books, cracking the interview code and algorithms)

**Comment by CLuiz** [comment]
Merge two sorted lists: https://www.geeksforgeeks.org/python-combining-two-sorted-lists/, I'd offer the second version as proof I understand how to use python. We can talk through how I'd handle this question on Friday. 

I like the third solution for the parens problem: https://www.geeksforgeeks.org/check-for-balanced-parentheses-in-python/

Both of these solutions are not what the FAANG companies would want to hear, but for other companies, it shows your knowledge and ability to implement things in python.

FAANG: Yes, but can you do this the hard way?
Normal companies: Nice! It looks like you can effectively use python builtins vs writing a bunch of unnecessary code.
