### ISSUE TITLE
ML Flashcard completion and study

### ISSUE THREAD

**Issue by Starsa** [Starsa/Mentorship#27]
Discuss flashcards reviewed and list any questions.
- [x] Monday
- [x]  Tuesday
- [x]  Wednesday
- [x]  Thursday
- [x]  Friday
- [x]  Saturday
- [x]  Sunday

**Comment by Starsa** [comment]
**ADA Boost vs. Gradient boost.**

AdaBoost is the first designed boosting algorithm with a particular loss function. 
Gradient Boosting is a generic algorithm that assists in searching the approximate solutions to the model. 

Gradient Boost is more flexible than AdaBoost.

**Comment by Starsa** [comment]
**Gradient**

The gradient of a function is a vector containing all its partial derivatives at some point
(repeat I know, just trying to focus on the wording)

**Comment by Starsa** [comment]
**Adjusted R2**

- A modified version of R-squared that has been adjusted for the number of predictors in the model. 
- It increases when the new term improves the model more than by chance. 
- It decreases when a predictor improves the model by less than expected.
- Once all correct features have been added, additional features should be peanalized

**Comment by Starsa** [comment]
**Agglomerative Clustering**
 -  All observations start as their own cluster
 - Clusters that meet a criteria are merged
 - Process is repeated, growing clusters, until some endpoint is met

**Comment by Starsa** [comment]
**AIC**
  - Used to compare models
    - like in feature selection

**Comment by CLuiz** [comment]
This is great! Good fodder for interview questions. AUC is one I typically poke at. R squared and adjusted R squared as well
