### ISSUE TITLE
Apply to open roles week of 8/30/21

### ISSUE THREAD

**Issue by Starsa** [Starsa/Mentorship#39]
### **Apply to Open Roles and track them here**

**Comment by Starsa** [comment]
**BuiltInNYC**

1. - [x] [TruGuard- Associate Data Analyst](https://jobs.lever.co/truveris/810ab104-db56-44e6-b89f-4b079b030ad2)

**BuiltInCo**

1. - [x] [Mercury Health- Sr. Data Analyst](https://www.builtincolorado.com/job/data/senior-data-analyst/93569) **Rejection Email**
2. - [x] [Pax8- Data Scientist](https://www.builtincolorado.com/job/data/data-scientist/94298) **Rejection Email**
3. - [x] [Pipeline- Data Science Developer, Python](https://www.builtincolorado.com/job/data/data-science-developer-python/94345)
4. - [x] [ContentSquare- Data Analyst](https://www.builtinnyc.com/job/data/data-analyst/113584) **Interviewing**
5. - [x] [Flex- Product Analyst](https://www.builtinnyc.com/job/data/product-analyst-lead/93348)**Rejection Email**
6. - [x] [Evolve- Data Scientist](https://www.builtincolorado.com/job/data/data-scientist-experimentation/91229)
7. - [x] [CirlceCI- Data Analyst](https://www.builtincolorado.com/job/data/data-analyst-product/76352)
8. - [x] [Quantum Metirc- Data Scientist](https://www.builtincolorado.com/job/data/data-scientist/75795)

**BuiltInSF**

1. - [x] [Human Interest-Sr Data Analyst](https://www.builtinsf.com/job/data/senior-data-analyst/65408) **Rejection Email**
2. - [x] [Wish- Data Scientist, Trust & Saftey](https://www.builtinsf.com/job/data/data-scientist-trust-safety/51486)
3. - [x] [Grand Rounds Health - Quantitative Researcher](https://www.builtinsf.com/job/data/quantitative-researcher-product-remote/49164) **Rejection Email**
4. - [x] [Affirm- Sr. Analyst Repayment Analytics](https://www.builtinsf.com/job/data/sr-analyst-repayment-analytics/52092) **Rejection Email**
5.  - [x] [Reddit- Data Scientist, Ads Machine Learning](https://www.builtinsf.com/job/data/data-scientist-ads-machine-learning/65047)
6. - [x] [Tempus- Machine Learning Engineer, NLP](https://www.builtinsf.com/job/data/machine-learning-engineer-nlp/59560) **Rejection Email**
7.  - [x] [Affirm- Analytics Lead, Pricing Automation](https://www.builtinsf.com/job/data/analytics-lead-pricing-automation/63385)
8. - [x] [Ginger- Machine Learning Engineer](https://www.builtinsf.com/job/data/machine-learning-engineer-nlp/12828)

**BuiltIn-Remote Roles**

1. - [x] [Doximity- Associate Data Analyst](https://www.builtinsf.com/job/data/associate-data-analyst-insights/59431)
2. - [x] [PicnicHealth- Machine Learning Applied Scientist](https://www.builtinsf.com/job/data/machine-learning-applied-scientist/33932)

**Comment by Starsa** [comment]
**LinkedIn**
1. - [x] [DISQO-Data Analyst](https://www.linkedin.com/jobs/view/2696957077/?refId=03ee7d5e-b309-3697-b4ac-c5f04e0d4a5f)
2. - [x] [WGSN- Data Analyst](https://www.linkedin.com/jobs/view/2682093527/?eBP=JOB_SEARCH_ORGANIC&recommendedFlavor=TOP_APPLICANT&refId=AQHhHTdyGSHH6REwpIwCdg%3D%3D&trackingId=3AN4I%2FJryF2NUeY%2F9Ifg4Q%3D%3D&trk=flagship3_search_srp_jobs)
3. - [x] [Interos- Associate Data Scientist](https://www.linkedin.com/jobs/view/2696201989/?eBP=JOB_SEARCH_ORGANIC&recommendedFlavor=TOP_APPLICANT&refId=AQHhHTdyGSHH6REwpIwCdg%3D%3D&trackingId=9G%2BbWcJPobtT57gwJ49Rlw%3D%3D&trk=flagship3_search_srp_jobs)
4. - [x] [Verana Health- NLP Quantitative Scientist](https://www.linkedin.com/jobs/view/2450943347/?alternateChannel=search&refId=AQHhHTdyGSHH6REwpIwCdg%3D%3D&trackingId=Nzx4D%2FA8ONE8a11fAVvY%2Bw%3D%3D&trk=d_flagship3_job_details) **Rejection Email**
5. - [x] [Olive- Data Scientist](https://www.linkedin.com/jobs/view/2699988422/?refId=d61c3252-5b7e-4e5d-9227-54eca4b8c55a&trk=flagship3_job_home_appliedjobs)
6. - [x] [PubW - Analyst, Analytics](https://www.linkedin.com/jobs/view/2698684299/?refId=d61c3252-5b7e-4e5d-9227-54eca4b8c55a&trk=flagship3_job_home_appliedjobs)
7. - [x] [Windstream - Data Science Engineer I](https://www.linkedin.com/jobs/view/2694825261/?refId=d61c3252-5b7e-4e5d-9227-54eca4b8c55a&trk=flagship3_job_home_appliedjobs)
8. - [x] [Neiman Marcus Group - Data Scientist](https://www.linkedin.com/jobs/view/2686338960/?refId=d61c3252-5b7e-4e5d-9227-54eca4b8c55a&trk=flagship3_job_home_appliedjobs)
9. - [x] [io173- Data Analyst](linkedin.com/jobs/view/2686264275/?refId=d61c3252-5b7e-4e5d-9227-54eca4b8c55a&trk=flagship3_job_home_appliedjobs)
10. - [x] [DataKind-Data Scientist](https://www.linkedin.com/jobs/view/2648805264/?alternateChannel=search&refId=Q%2Faxf2FDh2Uq9buaBR8ZQA%3D%3D&trackingId=LNBUem6FZEeSI%2B7nSh%2BknA%3D%3D)
11. - [x] [Spotify- Data Scientist- Productivity Engineering Insights](https://www.linkedin.com/jobs/view/2585929159/?alternateChannel=search&refId=p0dA%2FGatVDtIYABbaCTo0w%3D%3D&trackingId=ziRw49GUo3eLyQWqvD7V8w%3D%3D&trk=d_flagship3_search_srp_jobs)
12. - [x] [Meredith Corporation- Jr. Data Scientist](https://www.linkedin.com/jobs/view/2694753147/?refId=7f050816-702d-446b-860a-f352faa37fbd&trk=flagship3_job_home_savedjobs)
13. - [x] [AirBnB- Data Scientist](https://www.linkedin.com/jobs/view/2698145097/?refId=7f050816-702d-446b-860a-f352faa37fbd&trk=flagship3_job_home_savedjobs)
14. - [x] [vendr - Data Analyst](https://www.linkedin.com/jobs/view/2701084665/?refId=7f050816-702d-446b-860a-f352faa37fbd)
15. - [x] [XSELL - Data Scientist](https://www.linkedin.com/jobs/view/2692110214/?refId=a3d5e4cb-3952-4bbe-a560-64398d36a941)
16. - [x] [Outschool- Data Analyst](https://www.linkedin.com/jobs/view/2695068037/?refId=7f050816-702d-446b-860a-f352faa37fbd) **Rejection Email**
17. - [x] [AngelList- Venture Data Analyst](https://www.linkedin.com/jobs/view/2677468384/?refId=7f050816-702d-446b-860a-f352faa37fbd)
18. - [x] [Spotify- Data Scientist Accounting](https://www.linkedin.com/jobs/view/2676728995/?alternateChannel=search&refId=p0dA%2FGatVDtIYABbaCTo0w%3D%3D&trackingId=haeqsj1rBjGkMWG7Hsx7Rg%3D%3D)
19. - [x] [Athletic Greens - Data Scientist](https://www.linkedin.com/jobs/view/2691108047/?refId=653b61f3-532d-4a8d-9e41-afe5d0d3b984&trk=flagship3_job_home_appliedjobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_myitems_savedjobs%3BlAzqvARkRs2P0eJy3HyAXw%3D%3D)
20. - [x] [Onward Select- Data Analyst](https://www.linkedin.com/jobs/view/2701094441/?refId=653b61f3-532d-4a8d-9e41-afe5d0d3b984&trk=flagship3_job_home_appliedjobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_myitems_savedjobs%3BlAzqvARkRs2P0eJy3HyAXw%3D%3D)
21. - [x] [Brand I.D- Data Analyst](https://www.linkedin.com/jobs/view/2699572422/?refId=653b61f3-532d-4a8d-9e41-afe5d0d3b984&trk=flagship3_job_home_appliedjobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_myitems_savedjobs%3BlAzqvARkRs2P0eJy3HyAXw%3D%3D)
22. - [x] [Power Digital Marketing - Data Scientist](https://www.linkedin.com/jobs/view/2699824911/?refId=653b61f3-532d-4a8d-9e41-afe5d0d3b984&trk=flagship3_job_home_appliedjobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_myitems_savedjobs%3BlAzqvARkRs2P0eJy3HyAXw%3D%3D)
23. - [x] [dentsu- SQL/Python Engineer](https://www.linkedin.com/jobs/view/2584183693/?refId=653b61f3-532d-4a8d-9e41-afe5d0d3b984&trk=flagship3_job_home_appliedjobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_myitems_savedjobs%3BlAzqvARkRs2P0eJy3HyAXw%3D%3D)
24. - [x] [Control Risk- Data Analyst](https://www.linkedin.com/jobs/view/2702568498/?refId=653b61f3-532d-4a8d-9e41-afe5d0d3b984&trk=flagship3_job_home_appliedjobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_myitems_savedjobs%3BlAzqvARkRs2P0eJy3HyAXw%3D%3D)
25. - [x] [Spotify- Data Scientist, Advertising](https://www.linkedin.com/jobs/view/2706030529/)
26. - [x] [ShopShops- Data Analyst](https://www.linkedin.com/jobs/view/2696246940/?refId=18bf085e-1e23-4b47-b951-437f2941c7d0)
27. - [x] [Whirl- Data Analyst](https://www.linkedin.com/jobs/view/2706645423/?alternateChannel=search&refId=OdfqvHJWK4U2jRBBBlV9aQ%3D%3D&trackingId=jm8CRRr2FAhCrTKYpXfXJA%3D%3D&trk=d_flagship3_postapply_immediate_screener_modal)
28. - [x] [Byte- Data Analyst](https://www.linkedin.com/jobs/view/2704280156/?alternateChannel=search&refId=OdfqvHJWK4U2jRBBBlV9aQ%3D%3D&trackingId=XzACAJFIgfaKbb4gFiDwNw%3D%3D&trk=d_flagship3_postapply_immediate_skill_assessment)
29. - [x] [Experian- Data Modeling Analyst](https://www.linkedin.com/jobs/view/2681724570/?alternateChannel=search&refId=OdfqvHJWK4U2jRBBBlV9aQ%3D%3D&trackingId=hFUsMf7dk6iAHJva%2FRNRgA%3D%3D&trk=d_flagship3_postapply_immediate_skill_assessment)
30. - [x] [SRAX- Data Analyst](https://www.linkedin.com/jobs/view/2679919759/?alternateChannel=search&refId=OdfqvHJWK4U2jRBBBlV9aQ%3D%3D&trackingId=W3Sf%2FLc%2BmQA2LIkHJjgVLQ%3D%3D&trk=d_flagship3_postapply_immediate_skill_assessment) **Rejection Email**

**Comment by Starsa** [comment]
**AngelList**

1. - [x] [AngelList Talent- Senior Data Analyst](https://angel.co/company/angellist/jobs/627213-angellist-talent-senior-data-analyst) **Rejection Email**
2. - [x] [Slated- Data Scientist](https://angel.co/company/slated/jobs/1440879-data-scientist)

**Comment by CLuiz** [comment]
I love it! Every time I refresh more jobs are here!

**Comment by Starsa** [comment]
### **Slack Groups**

**SharpestMinds**

1. - [x] [wndrvr- AI/ML Developer Intern](https://jobs.jobvite.com/windriver/job/oOqMffwZ) **Rejection Email**


**Women In Tech**

1. - [x] [Surefoot-Digital Analyst](https://surefoot.me/jobs/digital-analyst/) **Rejection Email**

**Comment by CLuiz** [comment]
1. - [ ] https://builtin.com/jobs/remote/data-analytics/analytics/data-science/machine-learning?ni=2
2. - [x] https://builtin.com/job/data/data-scientist/67810
3. - [x] https://builtin.com/job/data/data-analyst-talent-operations/187131
4. - [x] https://builtin.com/job/data/growth-analyst/65680
5. - [x] https://builtin.com/job/data/data-scientist/188457

1. - [x] https://builtin.com/job/data/data-analyst/187129
2. - [x] https://builtin.com/job/data/senior-data-analyst/57714
3. - [ ] https://builtin.com/job/data/senior-data-analyst/185031 (already applied)
4. - [x] https://builtin.com/job/data/associate-data-technology-consultant/184577
5. - [x] https://builtin.com/job/data/analytical-linguist/57781


1. - [x] https://builtin.com/job/data/natural-language-processing-scientist-remote/70152
2. - [x] https://builtin.com/job/data/data-scientist-marketing-and-acquisition/68796
3. - [ ] https://builtin.com/job/data/data-scientist/56119
4. - [x] https://builtin.com/job/data/marketing-data-scientist/121576
5. - [x] https://builtin.com/job/data/data-scientist/61154


1. - [x] https://builtin.com/job/data/data-scientist/107058
2. - [x] https://builtin.com/job/data/machine-learning-engineer-nlp/70015
3. - [x] https://builtin.com/job/data/data-scientist/169152
4. - [x] https://builtin.com/job/data/data-scientist-marketing/169101
5. - [x] https://builtin.com/job/data/data-scientist/45126

Whew, 20 for ya. Definitely a  wide range in quality, but all recent and a few really good fits. Keep up the great work!

**Comment by CLuiz** [comment]
Figured out how to see nationwide remote on built:
https://builtin.com/jobs/remote/data-analytics/data-science/machine-learning?ni=2&page=6
(I ended on page 6, so plenty more there as well.)

**Comment by CLuiz** [comment]
This one comes with 35!!! days off: https://boards.greenhouse.io/crisistextline86/jobs/4640489003?t=c21201d33us

**Comment by Starsa** [comment]
**@CLuiz sent**

1. - [x] [Anti Evil Operations- German Speaking - reddit](https://boards.greenhouse.io/reddit/jobs/3342701)
2. - [x] [Data Scientist- reddit](https://boards.greenhouse.io/reddit/jobs/3432798)

**Comment by CLuiz** [comment]
I know a guy at Reddit if you are interested in an intro. Not a ds though - I think back end dev

**Comment by Starsa** [comment]
> I know a guy at Reddit if you are interested in an intro. Not a ds though - I think back end dev

That would be great!

**Comment by Starsa** [comment]
> This one comes with 35!!! days off: https://boards.greenhouse.io/crisistextline86/jobs/4640489003?t=c21201d33us

I think I already applied to this one through LinkedIn

**Comment by CLuiz** [comment]
> > This one comes with 35!!! days off: https://boards.greenhouse.io/crisistextline86/jobs/4640489003?t=c21201d33us
> 
> I think I already applied to this one through LinkedIn

I thought it looked familiar... was hoping it was a similar position vs the same.

**Comment by CLuiz** [comment]
> > I know a guy at Reddit if you are interested in an intro. Not a ds though - I think back end dev
> 
> That would be great!

Sent a request for a convo to this guy: https://www.linkedin.com/in/markistaylor/
