### ISSUE TITLE
Find ten interesting job descriptions

### ISSUE THREAD

**Issue by CLuiz** [Starsa/Mentorship#4]
Find ten interesting job descriptions to discuss. Focus on individual components of the descriptions that are of interest, vs finding 'the perfect fit'.

Due Thurs June 1

Acceptance Criteria:
- [x] Gather ten(ish) job descriptions to discuss on Thurs.

**Comment by Starsa** [comment]
1.  [Harnahan](https://www.linkedin.com/jobs/view/2571813801/?alternateChannel=search&refId=cr3r2wQHHf0dZTWnWS%2BZNQ%3D%3D&trackingId=H9iq0UmGKEnr2v%2Bzh5R5Sg%3D%3D&trk=d_flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BaXzibtD4TcmkyOXT7DLYMQ%3D%3D)
2. [Stitch Fix](https://www.linkedin.com/jobs/view/2534716614/?alternateChannel=search&refId=cr3r2wQHHf0dZTWnWS%2BZNQ%3D%3D&trackingId=w0kTaMnrrGRidsRG7SxWuA%3D%3D&trk=d_flagship3_search_srp_jobs&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3BXRW6PXq1THW7Q0uUrjsvCg%3D%3D)
3. [Spotify](https://ai-jobs.net/job/7385-data-scientist-music-analytics/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic)
4. [Optum](https://www.linkedin.com/jobs/view/nlp-data-scientist-remote-at-optum-2592188863?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic)
5. [Spotify](https://ai-jobs.net/job/7385-data-scientist-music-analytics/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic)
6. [AlphaSites](https://app.greenhouse.io/embed/job_app?token=3035209&s=LinkedIn&source=LinkedIn)

**Comment by CLuiz** [comment]
Ah, I saw that stitch fix job. I'll take a look at the others.

**Comment by Starsa** [comment]
I applied awhile ago to a similar position to the first Spotify job- data science music analytics... was very disappointed to get that rejection. I have interviewed once at spotify, and this is honestly dream company given my music background

**Comment by CLuiz** [comment]
Good context. Spotify is a good company (from what I hear), but there are other folks in the music space. I'd like to dig in on that a bit tomorrow am.
