### ISSUE TITLE
Develop a list of mentorship goals

### ISSUE THREAD

**Issue by CLuiz** [Starsa/Mentorship#5]
Aim for five or so. We will discuss and force-rank later this week.

Due: June 1

Acceptance criteria:
- [x] Create list
- [x] Discuss at Thurs June 1 meeting and re-rank if necessary
- [x] Add a note to the Goals & Notes board with the complete list

**Comment by Starsa** [comment]
Mentorship Goals:

- Find a job to continue developing NLP skills making over $95K
- Work on deeper understanding and communication of projects and ML techniques
- Develop NLP skills
- Work from an industry approach to problems

**Comment by CLuiz** [comment]
This is great!

Feel free to tic the box in the original issue if you complete a task.

**Comment by CLuiz** [comment]
@Starsa please add this to the goals and notes section. Update when you have thought through minimums and total comp stuff.

**Comment by Starsa** [comment]
Had a thought in terms of comp.

If I am being completely honest with myself; I am in this for $$. I walked away from doing something I loved that didn't make much money to live freely and comfortably. 

Yes, I want to do something for good or the good of the planet and get excited about recalibrating my skills(etc.), but when I quit singing my goal was to make all the $$. Additionally, I want to be the non-traditional breadwinner so my partner can be the artist (He is a ceramics artist), and not worry about how much income he is bringing in. 

I found something I am good at, and it's absolutely fun, but I don't have to love it as much as I did performing. 

Just a random thought I am leaving here until I retarget my comp goals.

**Comment by CLuiz** [comment]
Good context, thanks. I made a similar decision when I was searching for my first ds role. Max comp and then leverage the title to move into a better fit position next. Ideally, we can find you the cash you need at a place with interesting work. FYI, max comp == facebook (or hedge funds, but I don't think you have interest there), but there may be work-life balance issues. 

If salary is number 1, what is number 2? Is a 40 hour week important to you?
