### ISSUE TITLE
Gather Job & Salary Info to Discuss

### ISSUE THREAD

**Issue by CLuiz** [Starsa/Mentorship#6]
Acceptance Criteria:
- [x] Add resources and links below
- [x] Add link to this card on the 'Job and Interview Resources' note
- [x] Create follow-up task for Sara to review

**Comment by CLuiz** [comment]
Burch DS Salary info 2021
[2021-DSA-BW-Study-Webinar-PDF.pdf](https://github.com/Starsa/Mentorship/files/6735503/2021-DSA-BW-Study-Webinar-PDF.pdf)
[Uploading Burtch-Works-Study-DS_Analytics-2021.pdf…]()

**Comment by CLuiz** [comment]
Note to self: Add Robert Half info here!

**Comment by Starsa** [comment]
[levels.fyi](https://www.levels.fyi/?compare=Google,Facebook,Microsoft&track=Software%20Engineer)

**Comment by CLuiz** [comment]
Robert half info
[2021_Salary_Guide_Technology_NA (1).pdf](https://github.com/Starsa/Mentorship/files/6749066/2021_Salary_Guide_Technology_NA.1.pdf)

**Comment by CLuiz** [comment]
Robert Half Salary Calculator: https://www.roberthalf.com/salary-guide/calculator

**Comment by CLuiz** [comment]
Follow-up task created. Closing as complete.
