### ISSUE TITLE
Review Salary Data and Create a 'Personal Market Range'

### ISSUE THREAD

**Issue by CLuiz** [Starsa/Mentorship#9]
Review the information in #6 and create a personal range based on your experience, location, and target industries. I'd suggest coming up with numbers for data science roles and predictive analytics roles, and perhaps some target company numbers from levels.  State how each range was described (ie, Burthworks predictive analytics professional, 1 yoe) and we will discuss next week.

Acceptance Criteria:
- [x] Create several personal salary ranges across the ds and predictive analytics fields for discussion on Fri July 9th.

**Comment by Starsa** [comment]
**Salary Range Goals**
It looks like the range for 0-3 years falls between $80-$150K
- I want to personally aim for 
  - $95-$140
    - I feel like that is attainable given what I have already interviewed for
      - Spotify L2 0 years at the company and 1-year of exp is $140K
    - Predictive analytics is at the lower end of that range
    - That seems on par with the data in New Haven, CT (closest city)
  -  Cannot go lower than $90K
    - allowing for $90k given the position must be remote or in CT
